openapi: "3.0.0"
info:
  title: 'Dog Store'
  version: '0.1'
  description: 'A dog store example'
paths:
  /health/:
    get:
      tags:
        - Not implement
      responses:
        "200":
          description: OK
components:
  schemas:
    Dogs:
      type: object
      properties:
        objects:
          type: array
          items:
            $ref: '#/components/schemas/Dog'